- name: Install role at specific path
  community.general.ansible_galaxy_install:
    type: role
    name: gantsign.golang
    dest: /ansible/roles

- name: golang role
  include_role:
    name: gantsign.golang
  vars:
    golang_gopath: '{{ go_path }}'
    golang_install_dir: '/usr/local/go'