- name: Install collection 
  community.general.ansible_galaxy_install:
    type: collection
    name: gantsign.golang

- name: golang role
  import_role:
    name: gantsign.golang
  vars:
    golang_gopath: '{{ go_path }}'
    golang_install_dir: '/usr/local/go'