- hosts: all
  become: true
  user: root
  strategy: free

  roles:
    - set_vars
    - preliminar_checks
    - install_dependences
    - create_user
    - role: gantsign.golang
      golang_gopath: '{{ go_path }}'
      golang_install_dir: '/usr/local/go'
    - install_binary
    - setup_service
    - init_node
    - setup_configuration
    - start_service
    - post_install