- hosts: all
  become: true
  user: root
  strategy: free

  roles:
    - set_vars
    - preliminar_checks
    - install_dependences
    - create_user
    - golang
    - install_binary
    - setup_service
    - init_node
    - setup_configuration
    - start_service
    - post_install