- name: Install dependencies
  apt:
    pkg:
      - make
      - whois
      - gcc
      - jq
      - xinetd
      - acl
      - git
    update_cache: true
  become: true

- name: Install Go using gantsign.golang role
  include_role:
    name: gantsign.golang
  vars:
    golang_gopath: '{{ go_path }}'
    golang_install_dir: '/usr/local/go'


- name: Upgrade node
  apt:
    upgrade: yes
  become: true