- name: Set home_folder
  set_fact:
    home_folder: >-
      {%- if comm_user == "root" %}/root{%- else %}/home/{{ comm_user }}{%- endif %}
      
- name: Set sync_node_home_folder
  set_fact:
    sync_node_home_folder: >-
      {%- if sync_node_comm_user == "root" %}/root{%- else %}/home/{{ sync_node_comm_user }}{%- endif %}

- name: Get data from URL
  uri:
    url: "https://raw.githubusercontent.com/commercionetwork/chains/master/{{ chain_id }}/.data.json"
    method: GET
    return_content: yes
  register: chain_data

- name: Parse json into variable
  set_fact:
    parsed_data: "{{ chain_data.content | from_json}}"

- name: parse chain data content
  set_fact:
    seeds: "{{ parsed_data.Seeds }}"
    persistent_peers: "{{ parsed_data.Persistent_peers }}"
    checksum: "{{ parsed_data.Genesis_Checksum }}"

- name: set default trust rpc1
  set_fact:
    trust_rpc1: "{{ parsed_data.Trust_rpc1 }}"
  when: custom_trust_rpc1 is not defined or custom_trust_rpc1 == ''

- name: set custom trust rpc1
  set_fact:
    trust_rpc1: "{{ custom_trust_rpc1 }}"
  when: custom_trust_rpc1 is defined and custom_trust_rpc1 != ''

- name: set default trust rpc2
  set_fact:
    trust_rpc2: "{{ parsed_data.Trust_rpc2 }}"
  when: custom_trust_rpc2 is not defined or custom_trust_rpc2 == ''

- name: set custom trust rpc2
  set_fact:
    trust_rpc2: "{{ custom_trust_rpc2 }}"
  when: custom_trust_rpc2 is defined and custom_trust_rpc2 != ''

- name: set default bin version
  set_fact:
    bin_version: "{{ parsed_data.Release }}"
  when: custom_bin_version is not defined or custom_bin_version == ''

- name: set custom bin version
  set_fact:
    bin_version: "{{ custom_bin_version }}"
  when: custom_bin_version is defined and custom_bin_version != ''